language: node_js
node_js:
- '7.6.0'
before_install:
- npm install -g jest

jobs:
  include:
    - stage: Run Tests
      node_js: node
      script: npm test && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage